# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=254, verbose_name='Nome')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'APP',
                'verbose_name_plural': 'APP',
                'ordering': ['layer'],
            },
        ),
        migrations.CreateModel(
            name='CesFundiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('proprietar', models.CharField(max_length=50, verbose_name='Nome do Proprietário')),
                ('cpf_cnpj', models.CharField(max_length=50, verbose_name='CPF')),
                ('munic_uf', models.CharField(max_length=50, verbose_name='Município da Residência')),
                ('end_prop', models.CharField(max_length=100, verbose_name='Endereço da Residência')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('tipo_imove', models.CharField(max_length=20, verbose_name='Tipo de Imóvel')),
                ('cert_sigef', models.CharField(max_length=10, verbose_name='Certificado pelo SIGEF?')),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Área do Imóvel')),
                ('lote', models.CharField(max_length=15, verbose_name='Lote')),
                ('loc_geogra', models.CharField(max_length=50, verbose_name='Município Localizado')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Informação Fundiária (CES)',
                'verbose_name_plural': 'Informações Fundiária (CES)',
                'ordering': ['processo'],
            },
        ),
        migrations.CreateModel(
            name='CesVistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código da Vistoria')),
                ('sign_cod', models.CharField(max_length=50, verbose_name='Descrição do Código')),
                ('cod_fazend', models.CharField(max_length=50, verbose_name='Código da Fazenda')),
                ('proprietar', models.CharField(max_length=100, verbose_name='Nome Proprietário')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação da Negociação')),
                ('acesso', models.CharField(max_length=50, verbose_name='Tipo de Acesso')),
                ('nome_infra', models.CharField(max_length=50, verbose_name='Nome do Infrator')),
                ('tipo_infra', models.CharField(max_length=50, verbose_name='Tipo de Infração')),
                ('desc_infra', models.CharField(max_length=254, verbose_name='Descrição da Infração')),
                ('data_infra', models.CharField(max_length=50, verbose_name='Data da Infração')),
                ('hora_infra', models.CharField(max_length=50, verbose_name='Hora da Infração')),
                ('flagrante', models.CharField(max_length=50, verbose_name='Houve Flagrante?')),
                ('notificado', models.CharField(max_length=50, verbose_name='Houve Notificação?')),
                ('observacao', models.CharField(max_length=254, verbose_name='Observação')),
                ('point_x', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Coordenada E')),
                ('point_y', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Coordenada N')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Infracão',
                'verbose_name_plural': 'Infrações',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=254, verbose_name='Nome')),
                ('area', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Área')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Cota de Nível',
                'verbose_name_plural': 'Cotas de Nível',
                'ordering': ['layer'],
            },
        ),
    ]
